name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please provide as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: Describe the bug you've encountered
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: List the exact steps to reproduce the bug
      placeholder: "1. Go to '...'
        2. Click on '...'
        3. See the error."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Explain what you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Add any logs if applicable (use detail+summary if it is long)
      render: shell
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide system details
      placeholder: |
        OS: [e.g., Windows, macOS]
        Type: [e.g. CPU, Vulkan/GPU]
        Version: [e.g., 0.5.0, 0.6.1]
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Add any additional relevant information
