name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information.
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: Describe the feature you'd like to propose
    validations:
      required: true
  - type: textarea
    id: why-needed
    attributes:
      label: Why Is This Needed?
      description: Explain the problem or need for this feature
      placeholder: Describe the problem this solves
    validations:
      required: true
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Provide a user story
      placeholder: As a [role], I want to [action] so that [benefit]
    validations:
      required: true
  - type: textarea
    id: suggested-solutions
    attributes:
      label: Suggested Solutions
      description: Describe how this feature could be implemented
      placeholder: Outline potential implementation approaches
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any relevant log files, links, or resources
      placeholder: Add any supporting materials
