# .github/workflows/rust-check.yml
name: Rust Checks

on:
  pull_request:
    branches:
      - main

jobs:
  backend-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Rust
      - name: Install Rust (Stable)
        uses: dtolnay/rust-toolchain@stable

      # Run checks
      - name: Check Rust Formatting
        run: cd ./src-tauri; cargo fmt --all -- --check

      # Install 
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libasound2-dev
          touch ./src-tauri/resources/whisper-model.bin

      - name: Run Rust Lints
        run: cd ./src-tauri; cargo clippy -- -D warnings
