name: "test-openblas-dep"

on:
  push:
    branches:
      - gh-actions

jobs:
  find-open-blas:
    strategy:
      fail-fast: false

    runs-on: windows-latest
    steps:
      - name: Setup OpenBLAS
        run: |
          Invoke-WebRequest -Uri "https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.26/OpenBLAS-0.3.26-x64.zip" -OutFile "OpenBLAS-0.3.26-x64.zip"
          Expand-Archive -Path "OpenBLAS-0.3.26-x64.zip" -DestinationPath "openblas"

      - name: Echo Info
        shell: bash
        env:
          OPENBLAS_PATH: "./openblas"
        run: |
          echo "OpenBLAS:" $OPENBLAS_PATH
          ls -R $OPENBLAS_PATH
